[api]
API_KEY = "sk-olcxfdwhydoqndrutwriusyobofmmyorjpbwdcitskcopuxx"

[preprocess]
max_chunk_size = 1000

[tfidf]


[bm25]
k1 = 1.5
b = 0.75
epsilon = 0.25
save_index_path = "indexes/bm25_index"

[common]
top_k = 5
test_data_path = "data/test.jsonl"
train_data_path = "data/train.jsonl"
val_data_path = "data/val.jsonl"